import type { Edge, Node } from "reactflow";

// Dummy data untuk jaringan elektrikal - Dual PLTMG System
export const initialNodes: Node[] = [
  // ========== TITLE ==========
  {
    id: "text-1764848363644",
    type: "text",
    position: { x: 250, y: -112 },
    width: 126,
    height: 50,
    data: {
      label: "PLTMG 1",
      fontSize: 28,
      color: "#ffffff",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "text-1764848391100",
    type: "text",
    position: { x: 1755, y: -91 },
    width: 131,
    height: 50,
    data: {
      label: "PLTMG 2",
      fontSize: 28,
      color: "#ffffff",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "text-1764848265046",
    type: "text",
    position: { x: 1040, y: 619 },
    width: 91,
    height: 44,
    data: {
      label: "KOPEL",
      fontSize: 24,
      color: "#ffffff",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },

  // ========== PLTMG 1 SYSTEM (LEFT SIDE) ==========
  // Pembangkit 1
  {
    id: "pembangkit-1764846127048",
    type: "pembangkit",
    position: { x: 128, y: 15 },
    width: 60,
    height: 60,
    data: {
      label: "Pembangkit",
      power: "200",
      voltage: "20",
      type: "type3",
      status: "active",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "circuitBreaker-1764846131597",
    type: "circuitBreaker",
    position: { x: 128, y: 123 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "INVALID",
      voltage: "20",
      current: "100",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "trafo2Belitan-1764846171966",
    type: "trafo2Belitan",
    position: { x: 128, y: 235 },
    width: 60,
    height: 71,
    data: {
      label: "Trafo 2 Belitan",
      capacity: "100",
      voltageLevel: "HV/MV",
      ratio: "20/0.4",
      status: "active",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "circuitBreaker-1764847022302",
    type: "circuitBreaker",
    position: { x: 128, y: 363 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "CLOSE",
      voltage: "0.4",
      current: "150",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  // Pembangkit 2
  {
    id: "pembangkit-1764846353340",
    type: "pembangkit",
    position: { x: 441, y: 15 },
    width: 60,
    height: 60,
    data: {
      label: "Pembangkit",
      power: "200",
      voltage: "20",
      type: "type3",
      status: "active",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "circuitBreaker-1764846391332",
    type: "circuitBreaker",
    position: { x: 441, y: 123 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "OPEN",
      voltage: "20",
      current: "100",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "trafo2Belitan-1764846457794",
    type: "trafo2Belitan",
    position: { x: 441, y: 235 },
    width: 60,
    height: 71,
    data: {
      label: "Trafo 2 Belitan",
      capacity: "100",
      voltageLevel: "HV/MV",
      ratio: "20/0.4",
      status: "active",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "circuitBreaker-1764846482778",
    type: "circuitBreaker",
    position: { x: 441, y: 363 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "CLOSE",
      voltage: "0.4",
      current: "150",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  // Main Bus PLTMG 1
  {
    id: "bus-1764847294829",
    type: "bus",
    position: { x: 1, y: 491 },
    width: 940,
    height: 10,
    data: {
      label: "Bus PLTMG 1",
      voltage: "0.4",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  // Feeders PLTMG 1
  {
    id: "circuitBreaker-1764847315418",
    type: "circuitBreaker",
    position: { x: 128, y: 585 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "CLOSE",
      voltage: "0.4",
      current: "75",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "generator2-1764847404247",
    type: "generator2",
    position: { x: 128, y: 817 },
    width: 60,
    height: 63,
    data: {
      label: "Load 1",
      power: "150",
      voltage: "0.4",
      status: "active",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "circuitBreaker-1764847328667",
    type: "circuitBreaker",
    position: { x: 441, y: 585 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "CLOSE",
      voltage: "0.4",
      current: "75",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "generator2-1764847425738",
    type: "generator2",
    position: { x: 441, y: 817 },
    width: 60,
    height: 63,
    data: {
      label: "Load 2",
      power: "150",
      voltage: "0.4",
      status: "active",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  // Kopel
  {
    id: "circuitBreaker-1764847355867",
    type: "circuitBreaker",
    position: { x: 754, y: 585 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "CLOSE",
      voltage: "0.4",
      current: "0",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },

  // ========== PLTMG 2 SYSTEM (RIGHT SIDE) ==========
  // Kopel connector
  {
    id: "circuitBreaker-1764847719637",
    type: "circuitBreaker",
    position: { x: 1327, y: 585 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "CLOSE",
      voltage: "0.4",
      current: "0",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  // Main Bus PLTMG 2
  {
    id: "bus-1764848087697",
    type: "bus",
    position: { x: 1201, y: 491 },
    width: 937,
    height: 10,
    data: {
      label: "Bus PLTMG 2",
      voltage: "0.4",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  // Pembangkit 1
  {
    id: "pembangkit-1764848037969",
    type: "pembangkit",
    position: { x: 1639, y: 15 },
    width: 60,
    height: 60,
    data: {
      label: "Pembangkit",
      power: "200",
      voltage: "20",
      type: "type3",
      status: "active",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "circuitBreaker-1764848034912",
    type: "circuitBreaker",
    position: { x: 1639, y: 123 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "OPEN",
      voltage: "20",
      current: "100",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "trafo2Belitan-1764848029726",
    type: "trafo2Belitan",
    position: { x: 1639, y: 235 },
    width: 60,
    height: 71,
    data: {
      label: "Trafo 2 Belitan",
      capacity: "100",
      voltageLevel: "HV/MV",
      ratio: "20/0.4",
      status: "active",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "circuitBreaker-1764847967439",
    type: "circuitBreaker",
    position: { x: 1639, y: 363 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "CLOSE",
      voltage: "0.4",
      current: "150",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  // Pembangkit 2
  {
    id: "pembangkit-1764848206572",
    type: "pembangkit",
    position: { x: 1952, y: 15 },
    width: 60,
    height: 60,
    data: {
      label: "Pembangkit",
      power: "200",
      voltage: "20",
      type: "type3",
      status: "active",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "circuitBreaker-1764848198007",
    type: "circuitBreaker",
    position: { x: 1952, y: 123 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "CLOSE",
      voltage: "20",
      current: "100",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "trafo2Belitan-1764848180085",
    type: "trafo2Belitan",
    position: { x: 1952, y: 235 },
    width: 60,
    height: 71,
    data: {
      label: "Trafo 2 Belitan",
      capacity: "100",
      voltageLevel: "HV/MV",
      ratio: "20/0.4",
      status: "active",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "circuitBreaker-1764848008464",
    type: "circuitBreaker",
    position: { x: 1952, y: 363 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "CLOSE",
      voltage: "0.4",
      current: "150",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  // Feeders PLTMG 2
  {
    id: "circuitBreaker-1764847782884",
    type: "circuitBreaker",
    position: { x: 1639, y: 585 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "CLOSE",
      voltage: "0.4",
      current: "75",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "generator2-1764847876940",
    type: "generator2",
    position: { x: 1639, y: 817 },
    width: 60,
    height: 63,
    data: {
      label: "Load 3",
      power: "150",
      voltage: "0.4",
      status: "active",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "circuitBreaker-1764847840934",
    type: "circuitBreaker",
    position: { x: 1952, y: 585 },
    width: 60,
    height: 60,
    data: {
      label: "L",
      status: "CLOSE",
      voltage: "0.4",
      current: "75",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
  {
    id: "generator2-1764847922147",
    type: "generator2",
    position: { x: 1952, y: 817 },
    width: 60,
    height: 63,
    data: {
      label: "Load 4",
      power: "150",
      voltage: "0.4",
      status: "active",
    },
    style: {
      outline: "none",
      outlineOffset: "0px",
    },
  },
];

export const initialEdges: Edge[] = [
  // ========== PLTMG 1 System Connections (Active - Green) ==========
  // Pembangkit 1 chain
  {
    id: "edge-pembangkit-1-to-cb-1",
    source: "pembangkit-1764846127048",
    sourceHandle: "bottom",
    target: "circuitBreaker-1764846131597",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "20",
      targetVoltage: "20",
    },
  },
  {
    id: "edge-cb-1-to-trafo-1",
    source: "circuitBreaker-1764846131597",
    sourceHandle: "bottom",
    target: "trafo2Belitan-1764846171966",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "20",
      targetVoltage: "20",
    },
  },
  {
    id: "edge-trafo-1-to-cb-2",
    source: "trafo2Belitan-1764846171966",
    sourceHandle: "bottom",
    target: "circuitBreaker-1764847022302",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "0.4",
      targetVoltage: "0.4",
    },
  },
  {
    id: "reactflow__edge-circuitBreaker-1764847022302bottom-bus-1764847294829top-6",
    source: "circuitBreaker-1764847022302",
    sourceHandle: "bottom",
    target: "bus-1764847294829",
    targetHandle: "top-6",
    type: "smoothstep",
    animated: false,
    style: {
      stroke: "#ffffff",
      strokeWidth: 2,
      strokeDasharray: "0",
    },
    data: {
      isElectrical: true,
      isActive: false,
      edgeType: "smoothstep",
    },
  },

  // Pembangkit 2 chain
  {
    id: "edge-pembangkit-2-to-cb-3",
    source: "pembangkit-1764846353340",
    sourceHandle: "bottom",
    target: "circuitBreaker-1764846391332",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "20",
      targetVoltage: "20",
    },
  },
  {
    id: "edge-cb-3-to-trafo-2",
    source: "circuitBreaker-1764846391332",
    sourceHandle: "bottom",
    target: "trafo2Belitan-1764846457794",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "20",
      targetVoltage: "20",
    },
  },
  {
    id: "edge-trafo-2-to-cb-4",
    source: "trafo2Belitan-1764846457794",
    sourceHandle: "bottom",
    target: "circuitBreaker-1764846482778",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "0.4",
      targetVoltage: "0.4",
    },
  },
  {
    id: "edge-cb-4-to-bus-1",
    source: "circuitBreaker-1764846482778",
    sourceHandle: "bottom",
    target: "bus-1764847294829",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "0.4",
      targetVoltage: "0.4",
    },
  },

  // Bus to Feeders PLTMG 1
  {
    id: "reactflow__edge-bus-1764847294829bottom-6-circuitBreaker-1764847315418top",
    source: "bus-1764847294829",
    sourceHandle: "bottom-6",
    target: "circuitBreaker-1764847315418",
    targetHandle: "top",
    type: "smoothstep",
    animated: false,
    style: {
      stroke: "#ffffff",
      strokeWidth: 2,
      strokeDasharray: "0",
    },
    data: {
      isElectrical: true,
      isActive: false,
      edgeType: "smoothstep",
    },
  },
  {
    id: "edge-cb-5-to-load-1",
    source: "circuitBreaker-1764847315418",
    sourceHandle: "bottom",
    target: "generator2-1764847404247",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "0.4",
      targetVoltage: "0.4",
    },
  },
  {
    id: "edge-bus-1-to-cb-6",
    source: "bus-1764847294829",
    sourceHandle: "bottom",
    target: "circuitBreaker-1764847328667",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "0.4",
      targetVoltage: "0.4",
    },
  },
  {
    id: "edge-cb-6-to-load-2",
    source: "circuitBreaker-1764847328667",
    sourceHandle: "bottom",
    target: "generator2-1764847425738",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "0.4",
      targetVoltage: "0.4",
    },
  },

  // Kopel connection
  {
    id: "reactflow__edge-circuitBreaker-1764847355867top-bus-1764847294829bottom-30",
    source: "circuitBreaker-1764847355867",
    sourceHandle: "top",
    target: "bus-1764847294829",
    targetHandle: "bottom-30",
    type: "smoothstep",
    animated: false,
    style: {
      stroke: "#ffffff",
      strokeWidth: 2,
      strokeDasharray: "0",
    },
    data: {
      isElectrical: true,
      isActive: false,
      edgeType: "smoothstep",
    },
  },
  {
    id: "reactflow__edge-circuitBreaker-1764847355867bottom-circuitBreaker-1764847719637bottom",
    source: "circuitBreaker-1764847355867",
    sourceHandle: "bottom",
    target: "circuitBreaker-1764847719637",
    targetHandle: "bottom",
    type: "smoothstep",
    animated: false,
    style: {
      stroke: "#ffffff",
      strokeWidth: 2,
      strokeDasharray: "0",
    },
    data: {
      isElectrical: true,
      isActive: false,
      edgeType: "smoothstep",
    },
  },

  // ========== PLTMG 2 System Connections (Active - Green) ==========
  // Kopel to Bus 2
  {
    id: "reactflow__edge-bus-1764848087697bottom-6-circuitBreaker-1764847719637top",
    source: "bus-1764848087697",
    sourceHandle: "bottom-6",
    target: "circuitBreaker-1764847719637",
    targetHandle: "top",
    type: "smoothstep",
    animated: false,
    style: {
      stroke: "#ffffff",
      strokeWidth: 2,
      strokeDasharray: "0",
    },
    data: {
      isElectrical: true,
      isActive: false,
      edgeType: "smoothstep",
    },
  },

  // Pembangkit 1 chain (PLTMG 2)
  {
    id: "edge-pembangkit-3-to-cb-7",
    source: "pembangkit-1764848037969",
    sourceHandle: "bottom",
    target: "circuitBreaker-1764848034912",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "20",
      targetVoltage: "20",
    },
  },
  {
    id: "edge-cb-7-to-trafo-3",
    source: "circuitBreaker-1764848034912",
    sourceHandle: "bottom",
    target: "trafo2Belitan-1764848029726",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "20",
      targetVoltage: "20",
    },
  },
  {
    id: "edge-trafo-3-to-cb-8",
    source: "trafo2Belitan-1764848029726",
    sourceHandle: "bottom",
    target: "circuitBreaker-1764847967439",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "0.4",
      targetVoltage: "0.4",
    },
  },
  {
    id: "edge-cb-8-to-bus-2",
    source: "circuitBreaker-1764847967439",
    sourceHandle: "bottom",
    target: "bus-1764848087697",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "0.4",
      targetVoltage: "0.4",
    },
  },

  // Pembangkit 2 chain (PLTMG 2)
  {
    id: "edge-pembangkit-4-to-cb-9",
    source: "pembangkit-1764848206572",
    sourceHandle: "bottom",
    target: "circuitBreaker-1764848198007",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "20",
      targetVoltage: "20",
    },
  },
  {
    id: "edge-cb-9-to-trafo-4",
    source: "circuitBreaker-1764848198007",
    sourceHandle: "bottom",
    target: "trafo2Belitan-1764848180085",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "20",
      targetVoltage: "20",
    },
  },
  {
    id: "edge-trafo-4-to-cb-10",
    source: "trafo2Belitan-1764848180085",
    sourceHandle: "bottom",
    target: "circuitBreaker-1764848008464",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "0.4",
      targetVoltage: "0.4",
    },
  },
  {
    id: "reactflow__edge-circuitBreaker-1764848008464bottom-bus-1764848087697top-30",
    source: "circuitBreaker-1764848008464",
    sourceHandle: "bottom",
    target: "bus-1764848087697",
    targetHandle: "top-30",
    type: "smoothstep",
    animated: false,
    style: {
      stroke: "#ffffff",
      strokeWidth: 2,
      strokeDasharray: "0",
    },
    data: {
      isElectrical: true,
      isActive: false,
      edgeType: "smoothstep",
    },
  },

  // Bus to Feeders PLTMG 2
  {
    id: "edge-bus-2-to-cb-11",
    source: "bus-1764848087697",
    sourceHandle: "bottom",
    target: "circuitBreaker-1764847782884",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "0.4",
      targetVoltage: "0.4",
    },
  },
  {
    id: "edge-cb-11-to-load-3",
    source: "circuitBreaker-1764847782884",
    sourceHandle: "bottom",
    target: "generator2-1764847876940",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "0.4",
      targetVoltage: "0.4",
    },
  },
  {
    id: "reactflow__edge-bus-1764848087697bottom-30-circuitBreaker-1764847840934top",
    source: "bus-1764848087697",
    sourceHandle: "bottom-30",
    target: "circuitBreaker-1764847840934",
    targetHandle: "top",
    type: "smoothstep",
    animated: false,
    style: {
      stroke: "#ffffff",
      strokeWidth: 2,
      strokeDasharray: "0",
    },
    data: {
      isElectrical: true,
      isActive: false,
      edgeType: "smoothstep",
    },
  },
  {
    id: "edge-cb-12-to-load-4",
    source: "circuitBreaker-1764847840934",
    sourceHandle: "bottom",
    target: "generator2-1764847922147",
    targetHandle: "top",
    type: "customizable",
    animated: true,
    style: {
      stroke: "#22c55e",
      strokeWidth: 3,
      strokeDasharray: "5,5",
    },
    data: {
      isElectrical: true,
      isActive: true,
      sourceVoltage: "0.4",
      targetVoltage: "0.4",
    },
  },
];
